##############################################
#                                            #
#              Tokyo Night Theme             #
#                                            #
##############################################

# This theme was created by: https://github.com/pearcidar ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "rose-pine"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#c4b6c5"
full_screen_bg = "#141517"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#96aff2", "#c9aa95"]

#-- File Panel
file_panel_fg = "#c4b6c5"
file_panel_bg = "#141517"
file_panel_border = "#1c1d1f"
file_panel_border_active = "#666068"
file_panel_top_directory_icon = "#c9aa95"
file_panel_top_path = "#96aff2"
file_panel_item_selected_fg = "#5f86b0"
file_panel_item_selected_bg = "#1c1d1f"

#-- Footer
footer_fg = "#c4b6c5"
footer_bg = "#141517"
footer_border = "#5f86b0"
footer_border_active = "#8583bc"

#-- Sidebar
sidebar_fg = "#c4b6c5"
sidebar_bg = "#141517"
sidebar_title = "#8583bc"
sidebar_border = "#5f86b0"
sidebar_border_active = "#c9aa95"
sidebar_item_selected_fg = "#96aff2"
sidebar_item_selected_bg = "#1c1d1f"
sidebar_divider = "#666068"

#-- Modals
modal_fg = "#c4b6c5"
modal_bg = "#141517"
modal_border_active = "#5f86b0"
modal_cancel_fg = "#1c1d1f"
modal_cancel_bg = "#c4959c"
modal_confirm_fg = "#1c1d1f"
modal_confirm_bg = "#9bbdb8"

#-- Help Menu
help_menu_hotkey = "#c9aa95"
help_menu_title = "#c4959c"

#-- Special
cursor = "#c9aa95"
correct = "#9bbdb8"
error = "#c4959c"
hint = "#5f86b0"
cancel = "#c9aa95"
