#
# hydro - mimic Fish's hydro prompt
#

add_newline = false

# A minimal left prompt
format = "$directory$character"

# no right prompt
right_format = "$git_branch${custom.git_status_dirty}$git_status$cmd_duration$status"

# Timeout for commands executed by starship (in milliseconds)
command_timeout=2000

[username]
show_always = true
style_user = "blue"
style_root = "red"
format = '\[$user\] ($style)'

[character]
success_symbol = "[](bold blue)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold blue)"
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_visual_symbol = '[](bold yellow)'


[directory]
style = "blue"
truncation_length = 3
truncation_symbol = "…/"
#truncation_length = 1
#truncation_symbol = ""
#fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = '[$branch]($style)'
style = 'bold green'

[git_status]
format = "[($ahead_behind$stashed)]($style) "
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "•"
style = "white"
format="[$symbol]($style)"
shell = ["zsh", "--no-rcs", "--no-globalrcs"]

[cmd_duration]
format = '[$duration]($style) '
style = "yellow"

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[  $time]($style)'

[line_break]
disabled = true

[status]
disabled = false
pipestatus = true
format = '[$symbol$int]($style)'
symbol = '✘ '
pipestatus_format = '\[$pipestatus\]($style)'
